-- Creates the "Cold Email Campaign 6" table for the Santa Clara USD 3-email drip.
-- Mirrors the schema of "Cold Email Campaign 5" with sequence_step supporting
-- steps 1–3 for the three-email sequence.
--
-- Run this ONCE in the Supabase SQL Editor before importing contacts.

CREATE TABLE IF NOT EXISTS "Cold Email Campaign 6" (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          text NOT NULL,
  name           text,
  title          text,
  district       text,
  batch          text DEFAULT 'santa-clara',
  sequence_step  integer DEFAULT 1,
  last_emailed_at timestamptz,
  subject        text,
  body           text,
  opted_out      boolean DEFAULT false,
  unsubscribed_at timestamptz,
  unsubscribe_reason text,
  created_at     timestamptz DEFAULT now()
);

-- Index for fast unsubscribe lookups.
CREATE INDEX IF NOT EXISTS campaign6_unsubscribed_at_idx
  ON "Cold Email Campaign 6" (unsubscribed_at)
  WHERE unsubscribed_at IS NOT NULL;

-- Index for the workflow query (active, eligible contacts).
CREATE INDEX IF NOT EXISTS campaign6_active_contacts_idx
  ON "Cold Email Campaign 6" (sequence_step, opted_out)
  WHERE opted_out IS DISTINCT FROM true AND sequence_step <= 3;

-- ──────────────────────────────────────────────────────────
-- After running this SQL, import contacts via:
--   node scripts/import-campaign6-csv.js data/campaign6-contacts.csv
-- ──────────────────────────────────────────────────────────
