-- Creates the "Cold Email Campaign 2" table for the end-of-year summer drip.
-- Mirrors the schema of "Cold Email" so the workflow code can target it via
-- SUPABASE_TABLE="Cold Email Campaign 2".
--
-- Run this ONCE in the Supabase SQL Editor before importing contacts.

CREATE TABLE IF NOT EXISTS "Cold Email Campaign 2" (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          text NOT NULL,
  name           text,
  title          text,
  district       text,
  batch          text DEFAULT 'batch2',
  sequence_step  integer DEFAULT 1,
  last_emailed_at timestamptz,
  subject        text,
  body           text,
  opted_out      boolean DEFAULT false,
  unsubscribed_at timestamptz,
  unsubscribe_reason text,
  created_at     timestamptz DEFAULT now()
);

-- Index for fast unsubscribe lookups.
CREATE INDEX IF NOT EXISTS campaign2_unsubscribed_at_idx
  ON "Cold Email Campaign 2" (unsubscribed_at)
  WHERE unsubscribed_at IS NOT NULL;

-- Index for the workflow query (active, eligible contacts).
CREATE INDEX IF NOT EXISTS campaign2_active_contacts_idx
  ON "Cold Email Campaign 2" (sequence_step, opted_out)
  WHERE opted_out IS DISTINCT FROM true AND sequence_step <= 1;

-- ──────────────────────────────────────────────────────────
-- After running this SQL, import contacts via:
--   node scripts/import-campaign2-csv.js data/campaign2-contacts.csv
-- ──────────────────────────────────────────────────────────
